### PR TITLE
Replace _id sort with _seq_no in JobSweeper to fix fielddata error

### LINKED ISSUE #2037: [BUG] Alerting Job Scheduler fails to read from jobs indices when `indices.id_field_data.enabled` is set to false
## Description

Job Scheduler can fail while sweeping job indices when the cluster setting `indices.id_field_data.enabled` is set to `false`.

The sweeper appears to sort by `_id` during pagination / traversal of job documents:

- `JobSweeper.java`: https://github.com/opensearch-project/alerting/blob/528dcabcc853b931c5bed275f9024c3e967dfd9c/core/src/main/kotlin/org/opensearch/alerting/core/JobSweeper.kt#L322

Under normal circumstances this is not an issue, but when fielddata access on `_id` is disabled, the sweep fails with an error like:

> Fielddata access on the _id field is disallowed, you can re-enable it by updating the dynamic cluster setting: indices.id_field_data.enabled

As a result, Job Scheduler is unable to read from the jobs indices successfully.

## Impact

This can break job sweeping for users who have intentionally disabled `indices.id_field_data.enabled` at the cluster level.

## Expected behavior

Job Scheduler should either:

1. Avoid relying on `_id` sorting for sweeping job indices
3. Use an alternative sort field that does not depend on `_id` fielddata access

## Actual behavior

Sweeping job indices fails when `indices.id_field_data.enabled=false`.

## Example stack trace

```text
[2026-03-11T10:50:40,563][INFO ][o.o.j.s.JobSweeper       ] [] Error while sweeping shard [.opensearch-sap--job][0], error message: all shards failed
[2026-03-11T10:50:40,564][DEBUG][o.o.a.s.TransportSearchAction] [] [][.opendistro-ism-config][1]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[.opendistro-ism-config], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, expand_wildcards_hidden=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], routing='null', preference='_shards:1|_primary', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=null, allowPartialSearchResults=true, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, ccsMinimizeRoundtrips=true, source={"size":100,"query":{"match_all":{"boost":1.0}},"version":true,"seq_no_primary_term":true,"sort":[{"_id":{"order":"asc","missing":"_last","unmapped_type":"keyword"}}],"search_after":[""]}, cancelAfterTimeInterval=null, pipeline=null, phaseTook=false}] lastShard [true]
[2026-03-11T10:50:40,564][DEBUG][o.o.a.s.TransportSearchAction] [] #[null,java.lang.IllegalArgumentException]#All shards failed for phase: [query]
org.opensearch.OpenSearchException$3: Fielddata access on the _id field is disallowed, you can re-enable it by updating the dynamic cluster setting: indices.id_field_data.enabled
    at org.opensearch.OpenSearchException.guessRootCauses(OpenSearchException.java:710)
...
````

## Workaround

A current mitigation is to re-enable:

```json
{
  "persistent": {
    "indices.id_field_data.enabled": true
  }
}
```

or revert the setting to its default value (`true`).

### PR DESCRIPTION
**Pull request by manaswini1920**
### Description

 When indices.id_field_data.enabled is set to false, the JobSweeper fails with Fielddata access on the _id field is disallowed because it sorts by _id during search_after pagination.

This replaces FieldSortBuilder("_id") with FieldSortBuilder("_seq_no"). _seq_no has doc_values enabled by default (no fielddata needed) and is unique per shard, which the sweeper already scopes to via _shards preference.

Resolves #2037

### Related Issues
Resolves #2037

### Testing

```
**Before fix (on main):**                                                                                                                                                                                                                                      1. Started local cluster: ./gradlew :alerting:run
 2. Created a monitor — succeeded
3. Disabled _id fielddata: PUT _cluster/settings {"persistent": {"indices.id_field_data.enabled": false}}
4. Waited for sweeper cycle (~60s)
5. Result: sweeper fails repeatedly every cycle:
 

> [ERROR][o.o.a.c.JobSweeper] [integTest-0] [.opendistro-alerting-config][0] Error while sweeping shard [.opendistro-alerting-config][0]
> org.opensearch.action.search.SearchPhaseExecutionException: all shards failed
>   at org.opensearch.index.mapper.IdFieldMapper$IdFieldType.fielddataBuilder(IdFieldMapper.java:184)
> 

 **After fix:**
 1. Built with fix, replaced core jar in test cluster
 2. Disabled _id fielddata before creating any monitors
 3. Created first monitor — succeeded, sweeper scheduled it
 4. Created second monitor — succeeded, sweeper scheduled it
 5. Waited for sweeper cycle (~65s)
 6. Result: no fielddata errors, both monitors scheduled : 
 
> [INFO][o.o.a.c.s.JobScheduler] Scheduling jobId : Yvti45wBWj1CzDFgjaLp, name: test-sweeper-fix
> [INFO][o.o.a.c.s.JobScheduler] Scheduling jobId : cftr45wBWj1CzDFgzKLx, name: test-sweeper-fix-2


```

### Check List
- [X] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [X] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: core/src/main/kotlin/org/opensearch/alerting/core/JobSweeper.kt [hunk 1]
```diff
@@ -318,10 +318,9 @@ class JobSweeper(
                 .source(
                     SearchSourceBuilder.searchSource()
                         .version(true)
+                        .seqNoAndPrimaryTerm(true)
                         .sort(
-                            FieldSortBuilder("_id")
-                                .unmappedType("keyword")
-                                .missing("_last")
+                            FieldSortBuilder("_seq_no")
```
Comment (eirsep) [inline core/src/main/kotlin/org/opensearch/alerting/core/JobSweeper.kt]: Seq_no sorting throws mapper parsing exception - field not found when index is empty. Kindly test on local or integtest and a catch so that job sweeper doesnt fail and kill the executor schedule

**Comment by manaswini1920** [comment]
> Approving. @manaswini1920 could we take adding those integ tests as a fast follow-up item? Those seem like important cases to catch.

@AWSHurneyt  Added these in latest revision : both passed locally : 
- test sweeper works with id field data disabled — verifies the original bug fix
- test sweeper handles empty jobs index — verifies the unmappedType("long") fix
