### PR TITLE
Changed @Ignore to @AwaitsFix

### LINKED ISSUE #1244: [BUG] Forbidden annotation org.junit.Ignore used instead of AwaitsFix
**Problem**
- `./gradlew build` fails to run due to `org.junit.Ignore` being called in class `SecureWorkflowRestApiIT`.
- `Task :alerting:forbiddenApisTest FAILED Forbidden annotation use: org.junit.Ignore [Use AwaitsFix instead]`

**Solution**
- Use `AwaitsFix` Annotation Instead.

### PR DESCRIPTION
**Pull request by kennyzhang0819**
Closes #1244 

Changed @Ignore to @AwaitsFix in SecureWorkflowRestApiIT

*CheckList:*
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt [hunk 1]
```diff
@@ -63,7 +63,7 @@ import org.opensearch.test.junit.annotations.TestLogging
 import java.time.Instant
 
 // TODO investigate flaky nature of tests. not reproducible in local but fails in jenkins CI
-@Ignore
+@AwaitsFix(bugUrl = "Replace with issue URL")
```
Comment (AWSHurneyt) [inline alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt:66]: I created this issue to track the investigation of these flaky tests. Could you revise this PR to include the issue link as the `bugUrl`?
https://github.com/opensearch-project/alerting/issues/1246

Comment (kennyzhang0819) [reply alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt]: Sure! Just did that. @AWSHurneyt

**Review by AWSHurneyt — APPROVED** [review]

**Review by lezzago — APPROVED** [review]

**Comment by AWSHurneyt** [comment]
@kennyzhang0819 Looks like the auto backport for this PR failed. Could you please manually create a backport PR? To do that, you'd want to:
1. Create a dev branch from the `2.x` branch.
2. Copy the changes from this PR to that branch (I usually use [git cherry-pick](https://git-scm.com/docs/git-cherry-pick) to do this).
3. Create a new PR from your 2.x dev branch to the 2.x branch in [alerting repo](https://github.com/opensearch-project/alerting).
